parser: "@typescript-eslint/parser"
env:
  node: true
  es2022: true
extends:
  - metarhia
  - prettier
  - plugin:sonarjs/recommended
plugins:
  - sonarjs
  - "@typescript-eslint"
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-console: 'off'
