parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
env:
  node: true
  es2022: true
rules:
  no-console: 'off'
extends:
  - metarhia
  - plugin:sonarjs/recommended
  - prettier
plugins:
  - sonarjs
  - '@typescript-eslint'
